"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { SessionProvider } from 'next-auth/react';
import Header from "../components/navbar/Page";
import Footer from "../components/footer/Page";
import { siteMetadata } from "./SitMetaData";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "ResumeCraft",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <head>
        <title>{siteMetadata.title}</title>
        <meta name="description" content={siteMetadata.description} />
      </head>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Providers>
            <Header />
            {children}
            <Footer />
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
