"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { SessionProvider } from 'next-auth/react';
import Header from "../components/navbar/Page";
import Footer from "../components/footer/Page";
import { siteMetadata } from "./SitMetaData";
import { useState, useEffect } from 'react';
import LottieAnimation from "./lottieanimation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "ResumeCraft",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, session }) {
  const [showAnimation, setShowAnimation] = useState(true);
  useEffect(() => {
    const timer = setTimeout(() => {
      setShowAnimation(false);
    }, 4000); // 3 seconds delay

    return () => clearTimeout(timer);
  }, []);
  return (
    <html lang="en">
      <head>
        <title>{siteMetadata.title}</title>
        <meta name="description" content={siteMetadata.description} />
      </head>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Providers>
            {showAnimation && (
              <div className={`transition-opacity ${showAnimation ? 'opacity-100' : 'opacity-0'} duration-1000 ease-in-out fixed inset-0 flex items-center justify-center bg-white z-50`}>
                <LottieAnimation />
              </div>
            )}
            <div className={`transition-opacity ${showAnimation ? 'opacity-0' : 'opacity-100'} duration-1000 ease-in-out`}>
              {children}
            </div>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
